"""Add verification columns

Revision ID: b957ae9554be
Revises: 176f7ea140e3
Create Date: 2025-08-17 12:44:59.217306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b957ae9554be'
down_revision = '176f7ea140e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('verification_details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verification_details')
        batch_op.drop_column('verification_score')

    # ### end Alembic commands ###
